// demo.cpp - exercises every HZProtect SDK module and prints a report.
//   1) build (build.bat)  2) hzstamp build\demo.exe  3) run build\demo.exe
#include <cstdio>
#include <cstring>
#include "../src/sdk/hzprotect.h"
#include "config_blob.h"   // generated by hzblob from test/assets/config.json

// One integrity stamp slot; hzstamp fills it after the build.
HZ_DEFINE_STAMP(g_stamp);

static void hex(const uint8_t* p, int n) { for (int i = 0; i < n; ++i) printf("%02x", p[i]); }

static bool selftest_sha256() {
    uint8_t d[32];
    hz::sha256("abc", 3, d);
    const uint8_t want[32] = {0xba,0x78,0x16,0xbf,0x8f,0x01,0xcf,0xea,0x41,0x41,0x40,0xde,0x5d,0xae,0x22,0x23,
                              0xb0,0x03,0x61,0xa3,0x96,0x17,0x7a,0x9c,0xb4,0x10,0xff,0x61,0xf2,0x00,0x15,0xad};
    return memcmp(d, want, 32) == 0;
}

static bool selftest_aes() {
    // FIPS-197 AES-256 block vector
    uint8_t key[32]; for (int i = 0; i < 32; ++i) key[i] = (uint8_t)i;
    uint8_t blk[16]; for (int i = 0; i < 16; ++i) blk[i] = (uint8_t)(i*0x11);
    const uint8_t want[16] = {0x8e,0xa2,0xb7,0xca,0x51,0x67,0x45,0xbf,0xea,0xfc,0x49,0x90,0x4b,0x49,0x60,0x89};
    hz::Aes256 a; a.key_expand(key); a.encrypt_block(blk);
    if (memcmp(blk, want, 16) != 0) return false;
    // CTR round-trip
    uint8_t msg[40]; for (int i = 0; i < 40; ++i) msg[i] = (uint8_t)(i*7+1);
    uint8_t orig[40]; memcpy(orig, msg, 40);
    uint8_t nonce[16] = {1,2,3,4,5,6,7,8,0,0,0,0,0,0,0,0};
    hz::aes256_ctr(key, nonce, msg, 40);
    if (memcmp(msg, orig, 40) == 0) return false; // must have changed
    hz::aes256_ctr(key, nonce, msg, 40);
    return memcmp(msg, orig, 40) == 0;            // must round-trip
}

int main() {
    printf("HZProtect SDK demo v%s\n\n", HZPROTECT_VERSION_STR);

    printf("self-tests:  SHA-256 %s   AES-256 %s\n", selftest_sha256() ? "OK" : "FAIL", selftest_aes() ? "OK" : "FAIL");
    printf("build seed  : 0x%016llx  (changes every build -> all ciphertext differs)\n\n",
           (unsigned long long)HZ_BUILD_SEED);

    printf("secret string : %s\n", HZ_STR("super-secret-license-key-ABC123").c_str());
    printf("api endpoint  : %s\n\n", HZ_STR("https://api.internal.example/validate").c_str());

    // Embedded asset: encrypted at build time, decrypted ONLY here in memory,
    // wiped when 'cfg' goes out of scope. Plaintext never touches disk.
    {
        hz::ScopedBytes cfg = HZ_BLOB(config_blob).decrypt();
        printf("decrypted config blob (%zu bytes, RAM only):\n%s\n\n", cfg.len, cfg.c_str());
    } // cfg wiped here

    hz::DebugReport d = hz::debugger_scan();
    printf("anti-debug (score %d/14):\n", d.score());
    printf("  BeingDebugged %d  IsDbgPresent %d  RemoteDbg %d  NtGlobalFlag %d\n", d.peb, d.api, d.remote, d.globalflag);
    printf("  DebugPort %d  DebugObject %d  DebugFlags %d  HWBP %d  Timing %d\n", d.port, d.object, d.flags, d.hwbp, d.timing);
    printf("  ThreadHidden %d  CloseHandle %d  Int3 %d  DbgUiPatched %d  ParentDbg %d\n", d.hidden, d.closeh, d.int3, d.dbgui, d.parent);
    printf("  => debugger_present() = %s\n\n", hz::debugger_present() ? "YES" : "no");

    hz::VmReport v = hz::vm_scan();
    printf("anti-vm: hypervisorBit %d  knownVendor %d  vendor=\"%s\"  => in_vm=%s\n\n",
           v.hyperBit, v.knownVendor, v.vendor, hz::in_virtual_machine() ? "YES" : "no");

    hz::HookResult hk[16]; int scanned = 0;
    int hooks = hz::scan_hooks(hk, 16, &scanned);
    printf("inline-hooks: %d/%d WinAPI prologues hooked  => hooks_present()=%s\n", hooks, scanned, hooks ? "YES" : "no");

    char hwid[65]; hz::hwid_hex(hwid);
    printf("machine HWID: %s\n\n", hwid);

    hz::SectionHash s = hz::self_section_crc(".text");
    printf("self .text  crc32=0x%08X  sha256=", s.ok ? s.crc : 0);
    if (s.ok) hex(s.sha, 32); else printf("<unreadable>");
    printf("\n");

    hz::Integrity ig = hz::verify_stamp(g_stamp);
    const char* ign = ig == hz::Integrity::Ok ? "OK (unmodified)"
                   : ig == hz::Integrity::Tampered ? "TAMPERED"
                   : ig == hz::Integrity::Unstamped ? "unstamped (run hzstamp)"
                   : "unreadable";
    printf("integrity   verify_stamp() = %s\n", ign);
    return 0;
}
