// lictest.cpp - verify license files against the embedded public key.
//   lictest <license-file> [...]
// Prints the status of each. Used by the end-to-end license test in the build.
#define _CRT_SECURE_NO_WARNINGS
#include <cstdio>
#include <cstring>
#include <vector>
#include "../src/sdk/hz_license.h"
#include "license_pubkey.h" // generated by: hzlicense keygen priv.bin license_pubkey.h

static const char* statusName(hz::LicenseStatus s) {
    switch (s) {
        case hz::LicenseStatus::Valid:        return "VALID";
        case hz::LicenseStatus::BadFormat:    return "BAD_FORMAT";
        case hz::LicenseStatus::BadSignature: return "BAD_SIGNATURE";
        case hz::LicenseStatus::WrongMachine: return "WRONG_MACHINE";
        case hz::LicenseStatus::Expired:      return "EXPIRED";
        default: return "?";
    }
}

int main(int argc, char** argv) {
    if (argc < 2) { fprintf(stderr, "usage: lictest <license-file> [...]\n"); return 2; }
    for (int i = 1; i < argc; ++i) {
        FILE* f = fopen(argv[i], "rb");
        if (!f) { printf("%-28s -> CANNOT_OPEN\n", argv[i]); continue; }
        std::vector<char> buf; char tmp[512]; size_t n;
        while ((n = fread(tmp, 1, sizeof(tmp), f)) > 0) buf.insert(buf.end(), tmp, tmp + n);
        buf.push_back(0); fclose(f);

        hz::LicenseInfo li = hz::verify_license(buf.data(), HZ_LICENSE_PUBKEY);
        printf("%-28s -> %-13s features=0x%04x expiry=%llu\n",
               argv[i], statusName(li.status), li.features, (unsigned long long)li.expiry);
    }
    return 0;
}
