// hzblob.cpp - encrypt an asset file with AES-256-CTR (per-build master key +
// a fresh random nonce) and emit a C header that embeds the ciphertext. The
// app decrypts it in memory with HZ_BLOB(name) (see hz_blob.h).
//
//   hzblob <asset-in> <out-header.h> <name> <key.bin>
#define _CRT_SECURE_NO_WARNINGS
#include <cstdio>
#include <cstdint>
#include <cstring>
#include <vector>
#include <windows.h>
#include <bcrypt.h>
#pragma comment(lib, "bcrypt.lib")
#include "../sdk/hz_aes.h"

static bool readAll(const char* p, std::vector<uint8_t>& out) {
    FILE* f = fopen(p, "rb"); if (!f) return false;
    fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);
    if (n < 0) { fclose(f); return false; }
    out.resize((size_t)n);
    bool ok = n == 0 || fread(out.data(), 1, (size_t)n, f) == (size_t)n;
    fclose(f); return ok;
}

int main(int argc, char** argv) {
    if (argc < 5) { fprintf(stderr, "usage: hzblob <asset-in> <out-header.h> <name> <key.bin>\n"); return 2; }
    const char* in = argv[1]; const char* out = argv[2]; const char* name = argv[3]; const char* keyf = argv[4];

    std::vector<uint8_t> plain, key;
    if (!readAll(in, plain)) { fprintf(stderr, "hzblob: cannot read asset %s\n", in); return 1; }
    if (!readAll(keyf, key) || key.size() != 32) { fprintf(stderr, "hzblob: key %s must be 32 bytes\n", keyf); return 1; }

    uint8_t nonce[16];
    if (BCryptGenRandom(nullptr, nonce, 16, BCRYPT_USE_SYSTEM_PREFERRED_RNG) != 0) { fprintf(stderr, "hzblob: RNG failed\n"); return 1; }

    std::vector<uint8_t> cipher = plain;
    hz::aes256_ctr(key.data(), nonce, cipher.data(), cipher.size());

    FILE* h = fopen(out, "wb");
    if (!h) { fprintf(stderr, "hzblob: cannot write %s\n", out); return 1; }
    fprintf(h, "// generated by hzblob from %s - encrypted, regenerated every build\n#pragma once\n#include <cstddef>\n", in);
    fprintf(h, "static const unsigned char %s_cipher[] = {", name);
    for (size_t i = 0; i < cipher.size(); ++i) fprintf(h, "%s0x%02x", i ? "," : "", cipher[i]);
    if (cipher.empty()) fprintf(h, "0");
    fprintf(h, "};\n");
    fprintf(h, "static const unsigned char %s_nonce[16] = {", name);
    for (int i = 0; i < 16; ++i) fprintf(h, "%s0x%02x", i ? "," : "", nonce[i]);
    fprintf(h, "};\n");
    fprintf(h, "static const size_t %s_len = %zu;\n", name, cipher.size());
    fclose(h);

    printf("hzblob: %s -> %s  (%zu bytes encrypted)\n", in, out, cipher.size());
    return 0;
}
