// hzkeygen.cpp - pre-build step. Emits fresh random key material on every run so
// each BUILD of the protected app differs: a 64-bit seed (mixed into every
// HZ_STR compile-time key) and a 256-bit master key (used by hzblob / runtime
// blob decryption). Writes a C header for the compiler and a raw .bin for
// hzblob to read.
//
//   hzkeygen <out-header.h> <out-key.bin>
//
// The shipped binary is still stable (the integrity stamp works); only the
// NEXT build gets different key material.
#define _CRT_SECURE_NO_WARNINGS
#include <cstdio>
#include <cstdint>
#include <windows.h>
#include <bcrypt.h>
#pragma comment(lib, "bcrypt.lib")

static bool rng(uint8_t* buf, size_t len) {
    return BCryptGenRandom(nullptr, buf, (ULONG)len, BCRYPT_USE_SYSTEM_PREFERRED_RNG) == 0;
}

int main(int argc, char** argv) {
    if (argc < 3) { fprintf(stderr, "usage: hzkeygen <out-header.h> <out-key.bin>\n"); return 2; }

    uint8_t key[32], seed[8];
    if (!rng(key, 32) || !rng(seed, 8)) { fprintf(stderr, "hzkeygen: RNG failed\n"); return 1; }
    uint64_t s = 0; for (int i = 0; i < 8; ++i) s = (s << 8) | seed[i];

    FILE* h = fopen(argv[1], "wb");
    if (!h) { fprintf(stderr, "hzkeygen: cannot write %s\n", argv[1]); return 1; }
    fprintf(h, "// generated by hzkeygen - DO NOT COMMIT, regenerated every build\n");
    fprintf(h, "#pragma once\n#define HZ_HAVE_BUILD_KEYS 1\n");
    fprintf(h, "#define HZ_BUILD_SEED 0x%016llxULL\n", (unsigned long long)s);
    fprintf(h, "static const unsigned char HZ_BUILD_MASTER_KEY[32] = {");
    for (int i = 0; i < 32; ++i) fprintf(h, "%s0x%02x", i ? "," : "", key[i]);
    fprintf(h, "};\n");
    fclose(h);

    FILE* b = fopen(argv[2], "wb");
    if (!b) { fprintf(stderr, "hzkeygen: cannot write %s\n", argv[2]); return 1; }
    fwrite(key, 1, 32, b);
    fclose(b);

    printf("hzkeygen: seed=0x%016llx  key+header written\n", (unsigned long long)s);
    return 0;
}
