// hzlicense.cpp - offline license authority (keep the private key safe!).
//
//   hzlicense keygen <priv.bin> <pubkey.h>     generate an Ed25519 key pair
//   hzlicense hwid                             print THIS machine's HWID
//   hzlicense issue <priv.bin> --out <file> [--hwid <64hex|ANY>]
//            [--expiry <YYYY-MM-DD|never>] [--features <hexmask>]
#define _CRT_SECURE_NO_WARNINGS
#include <cstdio>
#include <cstdint>
#include <cstring>
#include <ctime>
#include <windows.h>
#include <bcrypt.h>
#pragma comment(lib, "bcrypt.lib")
#include "../sdk/hz_license.h"
#include "../sdk/hz_ed25519.h"

static bool readFile(const char* p, uint8_t* out, size_t want) {
    FILE* f = fopen(p, "rb"); if (!f) return false;
    size_t n = fread(out, 1, want, f); fclose(f); return n == want;
}
static int hx(char c){ if(c>='0'&&c<='9')return c-'0'; if(c>='a'&&c<='f')return c-'a'+10; if(c>='A'&&c<='F')return c-'A'+10; return -1; }

static int keygen(const char* privPath, const char* pubPath) {
    uint8_t seed[32], pk[32], sk[64];
    if (BCryptGenRandom(nullptr, seed, 32, BCRYPT_USE_SYSTEM_PREFERRED_RNG) != 0) { fprintf(stderr, "RNG failed\n"); return 1; }
    hz::ed::keypair_from_seed(pk, sk, seed);

    FILE* f = fopen(privPath, "wb"); if (!f) { fprintf(stderr, "cannot write %s\n", privPath); return 1; }
    fwrite(sk, 1, 64, f); fclose(f);

    f = fopen(pubPath, "wb"); if (!f) { fprintf(stderr, "cannot write %s\n", pubPath); return 1; }
    fprintf(f, "// generated by hzlicense keygen - embed this in your app\n#pragma once\n");
    fprintf(f, "static const unsigned char HZ_LICENSE_PUBKEY[32] = {");
    for (int i = 0; i < 32; ++i) fprintf(f, "%s0x%02x", i ? "," : "", pk[i]);
    fprintf(f, "};\n");
    fclose(f);
    printf("keygen: private key -> %s (64 bytes, KEEP SECRET)\n        public key  -> %s\n", privPath, pubPath);
    return 0;
}

static int issue(int argc, char** argv) {
    const char* priv = argv[2];
    const char* out = nullptr; const char* hwidHex = nullptr; const char* expiry = nullptr;
    uint32_t features = 0;
    for (int i = 3; i < argc; ++i) {
        if (!strcmp(argv[i], "--out") && i+1 < argc) out = argv[++i];
        else if (!strcmp(argv[i], "--hwid") && i+1 < argc) hwidHex = argv[++i];
        else if (!strcmp(argv[i], "--expiry") && i+1 < argc) expiry = argv[++i];
        else if (!strcmp(argv[i], "--features") && i+1 < argc) features = (uint32_t)strtoul(argv[++i], nullptr, 16);
    }
    if (!out) { fprintf(stderr, "issue: --out <file> required\n"); return 2; }

    uint8_t sk[64];
    if (!readFile(priv, sk, 64)) { fprintf(stderr, "issue: cannot read 64-byte key %s\n", priv); return 1; }

    hz::LicensePayload p; memset(&p, 0, sizeof(p));
    p.magic = hz::HZ_LICENSE_MAGIC; p.version = hz::HZ_LICENSE_VERSION;
    p.features = (uint16_t)features;
    p.issued = (uint64_t)time(nullptr);

    if (hwidHex && _stricmp(hwidHex, "ANY") != 0) {
        if (strlen(hwidHex) != 64) { fprintf(stderr, "issue: --hwid must be 64 hex chars or ANY\n"); return 2; }
        for (int i = 0; i < 32; ++i) { int a=hx(hwidHex[2*i]), b=hx(hwidHex[2*i+1]); if(a<0||b<0){fprintf(stderr,"bad hwid hex\n");return 2;} p.hwid[i]=(uint8_t)((a<<4)|b); }
    } // else leave zero = any machine

    if (expiry && _stricmp(expiry, "never") != 0) {
        int y, m, d;
        if (sscanf(expiry, "%d-%d-%d", &y, &m, &d) != 3) { fprintf(stderr, "issue: --expiry YYYY-MM-DD or never\n"); return 2; }
        struct tm t; memset(&t, 0, sizeof(t));
        t.tm_year = y - 1900; t.tm_mon = m - 1; t.tm_mday = d; t.tm_hour = 23; t.tm_min = 59; t.tm_sec = 59;
        time_t e = _mkgmtime(&t);
        if (e == (time_t)-1) { fprintf(stderr, "issue: bad date\n"); return 2; }
        p.expiry = (uint64_t)e;
    } // else 0 = perpetual

    uint8_t blob[hz::HZ_LICENSE_BLOB];
    memcpy(blob, &p, sizeof(p));
    hz::ed::sign_detached(blob + sizeof(p), blob, sizeof(p), sk);

    char b64[hz::HZ_LICENSE_BLOB * 2 + 8];
    hz::detail::b64enc(blob, hz::HZ_LICENSE_BLOB, b64);

    FILE* f = fopen(out, "wb"); if (!f) { fprintf(stderr, "issue: cannot write %s\n", out); return 1; }
    fprintf(f, "-----BEGIN HZ LICENSE-----\n%s\n-----END HZ LICENSE-----\n", b64);
    fclose(f);

    char when[32] = "never";
    if (p.expiry) { time_t e=(time_t)p.expiry; struct tm* g=gmtime(&e); strftime(when,sizeof(when),"%Y-%m-%d",g); }
    printf("issued: %s  features=0x%04x  expiry=%s  hwid=%s\n", out, p.features, when,
           hwidHex && _stricmp(hwidHex,"ANY") ? "bound" : "ANY");
    return 0;
}

int main(int argc, char** argv) {
    if (argc >= 2 && !strcmp(argv[1], "keygen") && argc >= 4) return keygen(argv[2], argv[3]);
    if (argc >= 2 && !strcmp(argv[1], "hwid")) { char h[65]; hz::hwid_hex(h); printf("%s\n", h); return 0; }
    if (argc >= 3 && !strcmp(argv[1], "issue")) return issue(argc, argv);
    fprintf(stderr,
        "usage:\n"
        "  hzlicense keygen <priv.bin> <pubkey.h>\n"
        "  hzlicense hwid\n"
        "  hzlicense issue <priv.bin> --out <file> [--hwid <64hex|ANY>] [--expiry <YYYY-MM-DD|never>] [--features <hex>]\n");
    return 2;
}
